server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      payment-start: payment-start
      payment-fail: payment-fail
      inventory-start: inventory-start
      product-validation-fail: product-validation-fail
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    org:
      apache:
        kafka: OFF